### ISSUE TITLE
Consider adding comments for additional plots and calculations

### ISSUE THREAD

**Issue by karl-project-review** [sperryOneWeb/intro-data-capstone-biodiversity#1]
https://github.com/sperryOneWeb/intro-data-capstone-biodiversity/blob/efd026198c96807d1f9a9858448d07ea6b6d5426/biodiversity_sperry/biodiversity.py#L65-L67
First off, kudos for going above and beyond by making extra plots like this! However, it is a good practice to make sure to add comments to the code to explain what it is doing. This will make it quicker and easier to read back through your projects and follow what is going on.

**Comment by sperryOneWeb** [comment]
Comments for all plots and extra analysis have been added.
