### ISSUE TITLE
Try to eliminate duplicate code

### ISSUE THREAD

**Issue by karl-project-review** [sperryOneWeb/intro-data-capstone-biodiversity#2]
https://github.com/sperryOneWeb/intro-data-capstone-biodiversity/blob/efd026198c96807d1f9a9858448d07ea6b6d5426/biodiversity_sperry/biodiversity.py#L185-L196
These lines are duplicates of  lines 145-171. It is a good practice to read back through projects like this to make sure there are no duplicate calculations or plots.

**Comment by sperryOneWeb** [comment]
This code is repeated to generate a new chart once the conservation_status "No Intervention" is added. Comments have been added to reflect this.
