### ISSUE TITLE
Avoid duplicate assignment statements

### ISSUE THREAD

**Issue by karl-project-review** [sperryOneWeb/intro-data-capstone-biodiversity#3]
https://github.com/sperryOneWeb/intro-data-capstone-biodiversity/blob/efd026198c96807d1f9a9858448d07ea6b6d5426/biodiversity_sperry/biodiversity.py#L317-L318
These assignments to the mammal protection rate variables are duplicates of those in lines 280 and 281. Try to avoid redundant code like this.

**Comment by sperryOneWeb** [comment]
I have removed the redundant statements and have replaced them with comments to keep the process explicit.
