### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by karl-project-review** [sperryOneWeb/intro-data-capstone-biodiversity#4]
(Exceeds Expectations)

Great work with this project! Not only did your code perform all of the necessary computations, but you went above and beyond by comparing the protection rates of mammals to all of the other categories instead of just birds and reptiles. To take your coding to the next level, though, I would recommend focusing on adding comments and avoiding redundancy to make your code more readable and efficient.

Your report gave a clear walk through of the analysis, and you used your additional plots effectively to help readers visualize what is going on. Apart from a typo (on the 'Definition of Endangered' slide it says 191 is 96.7% of the 5,541 species), this was an excellent overview of the project. I especially liked your recommendations for further studies to be performed. If you are interested, trying to perform the Tukey test would make a good learning exercise.

As an added challenge, think about how we might conduct a study to check for dependence between the different species' endangered status. What additional data might be useful for this study? What sort of tests would be appropriate? Do you think such a study is feasible on a wide scale?

Again, awesome job!

**Comment by sperryOneWeb** [comment]
Karl,

Thank you very much for your detailed and swift evaluation. I have addressed your other open issues and updated the pdf with the typo fixed.

**Comment by mjzanc** [comment]
Thank you so much for the kind review! I will continue to work on my coding to reduce redundancy and make my code as efficient as possible.
